{"name": "test_get_account_by_id", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute '_id'", "trace": "accounteapi = <accountapi.accountApi object at 0x0279A7D8>\n\n    def test_get_account_by_id(accounteapi:accountApi)->GetUserResult:\n        \"\"\" test get account\n        :param: bookapi->accountApi\n         :returns: TokenViewModel\n         \"\"\"\n          #The test will fail because of a bug - it says the user is not authorize but it is\n        mylogger.info(\"test for getting account by id\")\n        account =  accounteapi.get_account_by_id('98a9f32e-8c82-48ba-ac5b-8c5ca86bc82e')\n>       assert account._id == '98a9f32e-8c82-48ba-ac5b-8c5ca86bc82e'\nE       AttributeError: 'NoneType' object has no attribute '_id'\n\ntestsb.py:96: AttributeError"}, "description": " test get account\n    :param: bookapi->accountApi\n     :returns: TokenViewModel\n     ", "start": 1659804795940, "stop": 1659804796206, "uuid": "73f4a595-9c5f-49e9-80ba-eb39b40f64c4", "historyId": "0c00e37aabcf2a5b120e356d51f6458d", "testCaseId": "a134fa8f0fd3271bb5d8e5a5e50d8e86", "fullName": "testsb#test_get_account_by_id", "labels": [{"name": "suite", "value": "testsb"}, {"name": "host", "value": "VERED-PC"}, {"name": "thread", "value": "3136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testsb"}]}